# Generated by Django 6.0.6 on 2026-06-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoApiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('toman_rate', models.PositiveIntegerField(default=85000, verbose_name='قیمت دلار به تومان')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
