# Generated by Django 6.0.6 on 2026-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero', 'بخش Hero (تیتر اصلی)'), ('features', 'بخش ویژگی\u200cها'), ('about', 'بخش درباره ما'), ('cta', 'بخش دعوت به اقدام (CTA)'), ('contact', 'بخش ارتباط با ما / فوتر')], db_index=True, max_length=50, verbose_name='کلید بخش')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='زیرعنوان / توضیح کوتاه')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('icon', models.CharField(blank=True, help_text='مثال: fa-solid fa-bolt', max_length=100, verbose_name='کلاس آیکون (FontAwesome)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_sections/', verbose_name='تصویر')),
                ('link_url', models.URLField(blank=True, verbose_name='لینک')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='متن لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بخش صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای صفحه اصلی',
                'ordering': ['section_key', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='tronlnd', max_length=100, verbose_name='نام سایت')),
                ('home_hero_title', models.CharField(default='بازار معاملاتی tronlnd', max_length=255, verbose_name='تیتر اصلی صفحه اول')),
                ('home_hero_subtitle', models.CharField(default='خرید و فروش سریع و امن ارزهای دیجیتال', max_length=500, verbose_name='زیرتیتر صفحه اول')),
                ('home_cta_text', models.CharField(default='همین حالا شروع کنید', max_length=100, verbose_name='متن دکمه اصلی')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره پشتیبانی')),
                ('contact_telegram', models.CharField(blank=True, max_length=100, verbose_name='آی\u200cدی تلگرام')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
