# Generated by Django 6.0.6 on 2026-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepagesection_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='trx_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول تزون (TRX)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usdt_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول تتر (TRC20)'),
        ),
    ]
