# Generated by Django 6.0.6 on 2026-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_trx_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_account_holder',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام صاحب حساب'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره کارت سایت (برای خرید)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_iban',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره شبا سایت (برای خرید)'),
        ),
    ]
