# Generated by Django 6.0.6 on 2026-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_site_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن پشتیبانی'),
        ),
    ]
