# Generated by Django 6.0.6 on 2026-07-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_support_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='btc_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول بیتکوین (BTC)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='eth_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول اتریوم (ERC20)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sol_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول سولانا (SOL)'),
        ),
    ]
