# Generated by Django 6.0.7 on 2026-08-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesetting_btc_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_1_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن اعلامیه ۱'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_1_color',
            field=models.CharField(blank=True, default='cyan', max_length=20, verbose_name='رنگ اعلامیه ۱ (cyan, green, coral, warning)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_1_icon',
            field=models.CharField(blank=True, default='fa-solid fa-bullhorn', max_length=50, verbose_name='آیکون اعلامیه ۱ (مثال: fa-solid fa-bullhorn)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_1_text',
            field=models.TextField(blank=True, verbose_name='متن اعلامیه ۱'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_1_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان اعلامیه ۱'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_2_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن اعلامیه ۲'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_2_color',
            field=models.CharField(blank=True, default='green', max_length=20, verbose_name='رنگ اعلامیه ۲'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_2_icon',
            field=models.CharField(blank=True, default='fa-solid fa-gift', max_length=50, verbose_name='آیکون اعلامیه ۲'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_2_text',
            field=models.TextField(blank=True, verbose_name='متن اعلامیه ۲'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_2_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان اعلامیه ۲'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_3_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن اعلامیه ۳'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_3_color',
            field=models.CharField(blank=True, default='coral', max_length=20, verbose_name='رنگ اعلامیه ۳'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_3_icon',
            field=models.CharField(blank=True, default='fa-solid fa-bolt', max_length=50, verbose_name='آیکون اعلامیه ۳'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_3_text',
            field=models.TextField(blank=True, verbose_name='متن اعلامیه ۳'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_3_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان اعلامیه ۳'),
        ),
    ]
