# Generated by Django 6.0.7 on 2026-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting_announcement_1_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bnb_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول بینانس (BNB)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='pm_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول پرفکت مانی (PM)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='xrp_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول ریپل (XRP)'),
        ),
    ]
