# Generated by Django 6.0.7 on 2026-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesetting_bnb_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='toman_rate',
            field=models.PositiveIntegerField(default=85000, verbose_name='قیمت دلار به تومان'),
        ),
    ]
