# Generated by Django 6.0.6 on 2026-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_toman_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ton_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول تون کوین (TON)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='utop_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول یوتوپیا (UTOPIA)'),
        ),
    ]
