# Generated by Django 6.0.6 on 2026-09-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesetting_ton_wallet_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='toman_rate',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='trx_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول ترون (TRX)'),
        ),
    ]
