# Generated by Django 6.0.6 on 2026-09-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sitesetting_toman_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoapisetting',
            name='usd_toman_api_url',
            field=models.URLField(blank=True, default='https://api.exchangerate-api.com/v4/latest/USD', help_text='مثال: https://api.exchangerate-api.com/v4/latest/USD', verbose_name='آدرس API نرخ دلار به تومان'),
        ),
        migrations.AlterField(
            model_name='cryptoapisetting',
            name='toman_rate',
            field=models.PositiveIntegerField(default=85000, verbose_name='قیمت دلار به تومان (دستی)'),
        ),
    ]
