# Generated by Django 6.0.6 on 2026-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cryptoapisetting_usd_toman_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoapisetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='cryptoapisetting',
            name='usd_toman_api_url',
            field=models.URLField(blank=True, default='https://open.er-api.com/v6/latest/USD', verbose_name='آدرس API نرخ دلار به تومان'),
        ),
    ]
