# Generated by Django 6.0.7 on 2026-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cryptoapisetting_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoapisetting',
            name='usd_toman_api_url',
            field=models.URLField(blank=True, default='https://api.nerkh.io/v2/prices/json/lite/currency', verbose_name='آدرس API نرخ دلار به تومان'),
        ),
        migrations.CreateModel(
            name='CachedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('usd_toman', 'USD to Toman'), ('crypto_price', 'Crypto Price (USD)')], db_index=True, max_length=20)),
                ('symbol', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'نرخ ذخیره شده',
                'verbose_name_plural': 'نرخ\u200cهای ذخیره شده',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['rate_type', 'symbol', '-fetched_at'], name='core_cached_rate_ty_db1aa8_idx')],
            },
        ),
    ]
