# Generated by Django 6.0.7 on 2026-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bnb_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس بینانس'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='btc_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس بیت کوین'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس اتریум'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pm_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس perfect money'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sol_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس سولانا'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trx_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس ترون'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس تتر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xrp_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس ریپل'),
        ),
    ]
