# Generated by Django 6.0.6 on 2026-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bnb_address_customuser_btc_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bnb_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی بینانس'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='btc_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی بیت کوین'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eth_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی اتریوم'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pm_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='موجودی پرفکت مانی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sol_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی سولانا'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trx_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی ترون'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی تتر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xrp_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی ریپل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس اتریوم'),
        ),
    ]
