# Generated by Django 6.0.6 on 2026-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_bnb_balance_customuser_btc_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ton_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس تون کوین'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ton_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی تون کوین'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utop_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس یوتوپیا'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utop_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='موجودی یوتوپیا'),
        ),
    ]
