# Generated by Django 6.0.6 on 2026-06-16 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش')], max_length=10)),
                ('crypto_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=25)),
                ('status', models.CharField(choices=[('pending', 'در دست بررسی'), ('done', 'تمام شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
