# Generated by Django 6.0.6 on 2026-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_crypto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در دست بررسی'), ('done', 'تمام شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
    ]
