# Generated by Django 6.0.6 on 2026-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositor_card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositor_shaba_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiat_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiat_deposit_type',
            field=models.CharField(blank=True, choices=[('CARD_TO_CARD', 'کارت به کارت'), ('SHABA', 'واریز از طریق شبا')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='crypto_name',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('TRX', 'Tron')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True),
        ),
    ]
