# Generated by Django 6.0.6 on 2026-07-02 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='هش تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='crypto_name',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('TRX', 'Tron')], max_length=20, null=True, verbose_name='نوع ارز'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='depositor_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت واریز کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='depositor_shaba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا واریز کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fiat_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مبلغ ریالی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fiat_deposit_type',
            field=models.CharField(blank=True, choices=[('CARD_TO_CARD', 'کارت به کارت'), ('SHABA', 'واریز از طریق شبا')], max_length=50, null=True, verbose_name='نوع واریز ریالی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='request_type',
            field=models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش')], max_length=10, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('reviewing', 'در حال بررسی'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
