# Generated by Django 6.0.6 on 2026-07-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transaction_transaction_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت مدیریت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='final_approval',
            field=models.BooleanField(default=False, verbose_name='تایید نهایی مدیریت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه واریز'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس کیف پول'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending_transfer', 'در انتظار ارسال'), ('pending_review', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
