# Generated by Django 6.0.7 on 2026-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_admin_note_transaction_final_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='depositor_card_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='depositor_shaba_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fiat_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fiat_deposit_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه واریزی بانکی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس مقصد'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchaser_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت خریدار'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchaser_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی خریدار'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchaser_shaba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا خریدار'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت فروشنده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی فروشنده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_shaba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا فروشنده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address_bnb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس کیف پول BNB'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address_btc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس کیف پول BTC'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address_sol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس کیف پول SOL'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('rejected', 'رد شد'), ('completed', 'انجام شد')], default='paid', max_length=20, verbose_name='وضعیت'),
        ),
    ]
