# Generated by Django 6.0.6 on 2026-09-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_transaction_depositor_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='crypto_name',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('TRX', 'Tron'), ('XRP', 'Ripple'), ('PM', 'Perfect Money'), ('TON', 'Toncoin'), ('UTOPIA', 'Utopia')], max_length=20, null=True, verbose_name='نوع ارز'),
        ),
    ]
